version: '3'
services:
  service1:
    image: "cmacica-service1:latest"
    build:
      context: java/
      dockerfile: ./Dockerfile
    ports:
      - 8080:8090
  website:
    image: "cmacica-web1:latest"
    build:
      context: angular3/
      dockerfile: ./Dockerfile
    ports:
      - 8081:80
  app:
    image: nginx:alpine
    ports:
      - 8083:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
