version: '3'

services:
  app:
    image: nginx:alpine
    ports:
      #- 9082:80
      - 9090:8083
    volumes:
      - ./volume:/usr/share/nginx/html:ro
      - ./volume/nginx.conf:/etc/nginx/nginx.conf:ro
